### ISSUE TITLE
sled doesn't exit properly

### ISSUE THREAD

**Issue by fridtjof** [shinyblink/sled#66]
Platform: SDL2 on macOS 10.14.2

after pressing Ctrl+C, sled hangs somewhere at or after https://github.com/shinyblink/sled/blob/f34162047afbfef99dde41f983abd8e9c1e6edfa/src/mod.c#L157

**Comment by vifino** [comment]
Since I don't have a Mac(*), you're gonna have to debug this.

**Comment by fridtjof** [comment]
This also affects at least macOS 10.13.

**Comment by fridtjof** [comment]
This is directly related to https://github.com/shinyblink/sled/commit/a5a29da2ea40f2d21af15ab13d8666b6df8e49dd - sled hangs in this stacktrace:


![](https://cdn.discordapp.com/attachments/382972453481218065/531645178587512834/unknown.png)
