### ISSUE TITLE
--filter without parameter produces segmentation

### ISSUE THREAD

**Issue by SquallHalle** [shinyblink/sled#97]
sudo  ./sled -o "rpi_hub75: --led-rows=64 --led-cols=64  --led-chain=6 --led-pixel-mapper=U-mapper;Rotate:180" --filter

gave me a segmentation fault

**Comment by vifino** [comment]
Filters sit inbetween the graphics (gfx) modules and the output (out) modules.
They can do things like gamma correction or mapping the matrix differently, for example folding it.

There should be more robust option parsing, there isn't much handling incorrect use there.
